# Generated by Django 2.2.2 on 2019-06-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=604, null=True)),
                ('position', models.CharField(blank=True, default=None, max_length=604, null=True)),
            ],
        ),
    ]
